
[env]
TERM = "xterm-256color"

[window]
dynamic_padding = false
opacity = 0.9
option_as_alt = "Both"
[window.padding]
x = 16
y = 16

[font]
size = 18

[font.bold]
family = "SauceCodePro Nerd Font"
style = "Heavy"

[font.bold_italic]
family = "SauceCodePro Nerd Font"
style = "Heavy Italic"

[font.italic]
family = "SauceCodePro Nerd Font"
style = "Medium Italic"

[font.normal]
family = "SauceCodePro Nerd Font"
style = "Medium"

[general]
live_config_reload = true
import = ["~/.config/alacritty/catppuccin-mocha.toml"]

[[keyboard.bindings]]
key = "Back"
mods = "Super"
chars = "\u0015"
