import = ["~/.config/alacritty/catppuccin-mocha.toml"]

live_config_reload = true

[env]
TERM = "xterm-256color"

[window]
dynamic_padding = false
opacity = 0.9
option_as_alt = "Both"

[font]
size = 18

[font.bold]
family = "SauceCodePro Nerd Font"
style = "Heavy"

[font.bold_italic]
family = "SauceCodePro Nerd Font"
style = "Heavy Italic"

[font.italic]
family = "SauceCodePro Nerd Font"
style = "Medium Italic"

[font.normal]
family = "SauceCodePro Nerd Font"
style = "Medium"
